services:
  fshare:
    image: ghcr.io/onur/fshare:latest
    ports:
      - 8080:8080
    environment:
      - AWS_BUCKET=test
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=12345678
      - AWS_ENDPOINT_URL=http://rustfs:9000/
  rustfs:
    image: rustfs/rustfs:1.0.0-alpha.76
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      RUSTFS_ACCESS_KEY: admin
      RUSTFS_SECRET_KEY: 12345678
      RUSTFS_CONSOLE_ENABLE: true
    volumes:
      - rustfs:/data

volumes:
  rustfs:
